---
source_pkg: "https://github.com/prometheus/node_exporter"
pkg_name: node_exporter
exec: node_exporter
node_exporter_version: "1.9.0"
service_file: node_exporter.service
service_name: node_exporter
